//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionesDolar
    {
        public System.DateTime Fecha { get; set; }
        public string BilleteCompra { get; set; }
        public string BilleteVenta { get; set; }
        public Nullable<decimal> Compra { get; set; }
        public Nullable<decimal> Venta { get; set; }
    }
}
