//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> LluviaDiariaSantaFe { get; set; }
        public Nullable<decimal> LluviaMensualSantaFe { get; set; }
        public Nullable<decimal> LluviaAnualSantaFe { get; set; }
        public Nullable<decimal> CotizacionDolar { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioSoja { get; set; }
        public Nullable<decimal> PrecioPromedioMensualSoja { get; set; }
        public Nullable<decimal> PrecioPromedioAnualSoja { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioTrigo { get; set; }
        public Nullable<decimal> PrecioPromedioMensualTrigo { get; set; }
        public Nullable<decimal> PrecioPromedioAnualTrigo { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioMaiz { get; set; }
        public Nullable<decimal> PrecioPromedioMensualMaiz { get; set; }
        public Nullable<decimal> PrecioPromedioAnualMaiz { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioSojaUSD { get; set; }
        public Nullable<decimal> PrecioPromedioMensualSojaUSD { get; set; }
        public Nullable<decimal> PrecioPromedioAnualSojaUSD { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioTrigoUSD { get; set; }
        public Nullable<decimal> PrecioPromedioMensualTrigoUSD { get; set; }
        public Nullable<decimal> PrecioPromedioAnualTrigoUSD { get; set; }
        public Nullable<decimal> PrecioPromedioDiarioMaizUSD { get; set; }
        public Nullable<decimal> PrecioPromedioMensualMaizUSD { get; set; }
        public Nullable<decimal> PrecioPromedioAnualMaizUSD { get; set; }
        public Nullable<decimal> SuperficieSembradaSojaBuenosAires { get; set; }
        public Nullable<decimal> SuperficieSembradaSojaCordoba { get; set; }
        public Nullable<decimal> SuperficieSembradaSojaSantaFe { get; set; }
        public Nullable<decimal> SuperficieSembradaMaizBuenosAires { get; set; }
        public Nullable<decimal> SuperficieSembradaMaizCordoba { get; set; }
        public Nullable<decimal> SuperficieSembradaMaizSantaFe { get; set; }
        public Nullable<decimal> SuperficieSembradaTrigoBuenosAires { get; set; }
        public Nullable<decimal> SuperficieSembradaTrigoCordoba { get; set; }
        public Nullable<decimal> SuperficieSembradaTrigoSantaFe { get; set; }
        public Nullable<decimal> SuperficieCosechadaSojaBuenosAires { get; set; }
        public Nullable<decimal> SuperficieCosechadaSojaCordoba { get; set; }
        public Nullable<decimal> SuperficieCosechadaSojaSantaFe { get; set; }
        public Nullable<decimal> SuperficieCosechadaMaizBuenosAires { get; set; }
        public Nullable<decimal> SuperficieCosechadaMaizCordoba { get; set; }
        public Nullable<decimal> SuperficieCosechadaMaizSantaFe { get; set; }
        public Nullable<decimal> SuperficieCosechadaTrigoBuenosAires { get; set; }
        public Nullable<decimal> SuperficieCosechadaTrigoCordoba { get; set; }
        public Nullable<decimal> SuperficieCosechadaTrigoSantaFe { get; set; }
        public Nullable<decimal> ProduccionSojaBuenosAires { get; set; }
        public Nullable<decimal> ProduccionSojaCordoba { get; set; }
        public Nullable<decimal> ProduccionSojaSantaFe { get; set; }
        public Nullable<decimal> ProduccionMaizBuenosAires { get; set; }
        public Nullable<decimal> ProduccionMaizCordoba { get; set; }
        public Nullable<decimal> ProduccionMaizSantaFe { get; set; }
        public Nullable<decimal> ProduccionTrigoBuenosAires { get; set; }
        public Nullable<decimal> ProduccionTrigoCordoba { get; set; }
        public Nullable<decimal> ProduccionTrigoSantaFe { get; set; }
        public Nullable<decimal> RendimientoSojaBuenosAires { get; set; }
        public Nullable<decimal> RendimientoSojaCordoba { get; set; }
        public Nullable<decimal> RendimientoSojaSantaFe { get; set; }
        public Nullable<decimal> RendimientoMaizBuenosAires { get; set; }
        public Nullable<decimal> RendimientoMaizCordoba { get; set; }
        public Nullable<decimal> RendimientoMaizSantaFe { get; set; }
        public Nullable<decimal> RendimientoTrigoBuenosAires { get; set; }
        public Nullable<decimal> RendimientoTrigoCordoba { get; set; }
        public Nullable<decimal> RendimientoTrigoSantaFe { get; set; }
        public Nullable<decimal> LluviaDiariaBuenosAires { get; set; }
        public Nullable<decimal> LLuviaMensualBuenosAires { get; set; }
        public Nullable<decimal> LluviaAnualBuenosAires { get; set; }
        public Nullable<int> CantidadIncendiosAnualesBuenosAires { get; set; }
        public Nullable<int> CantidadIncendiosAnualesCordoba { get; set; }
        public Nullable<int> CantidadIncendiosAnualesSantaFe { get; set; }
        public Nullable<int> PromedioIncendiosMensualesBuenosAires { get; set; }
        public Nullable<int> PromedioIncendiosMensualesCordoba { get; set; }
        public Nullable<int> PromedioIncendiosMensualesSantaFe { get; set; }
        public Nullable<decimal> VariacionTrigoDiaAnterior { get; set; }
        public Nullable<decimal> VariacionSojaDiaAnterior { get; set; }
        public Nullable<decimal> VariacionMaizDiaAnterior { get; set; }
        public Nullable<decimal> VariacionTrigoTresDias { get; set; }
        public Nullable<decimal> VariacionSojaTresDias { get; set; }
        public Nullable<decimal> VariacionMaizTresDia { get; set; }
        public Nullable<decimal> VariacionTrigoSieteDias { get; set; }
        public Nullable<decimal> VariacionSojaSieteDias { get; set; }
        public Nullable<decimal> VariacionMaizSieteDias { get; set; }
    }
}
