//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LluviasRegistradas
    {
        public System.DateTime Fecha { get; set; }
        public string Provincia { get; set; }
        public string Departamento { get; set; }
        public string Localidad { get; set; }
        public Nullable<decimal> Registro { get; set; }
        public int Id { get; set; }
    }
}
