//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnirEntities : DbContext
    {
        public UnirEntities()
            : base("name=UnirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<LluviasRegistradas> LluviasRegistradas { get; set; }
        public virtual DbSet<Promedio_diario_maiz> Promedio_diario_maiz { get; set; }
        public virtual DbSet<Promedio_diario_soja> Promedio_diario_soja { get; set; }
        public virtual DbSet<Promedio_diario_trigo> Promedio_diario_trigo { get; set; }
        public virtual DbSet<CotizacionesDolar> CotizacionesDolar { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<LluviasAnuales> LluviasAnuales { get; set; }
        public virtual DbSet<LluviasAnualesBuenosAires> LluviasAnualesBuenosAires { get; set; }
        public virtual DbSet<LluviasAnualesSantaFe> LluviasAnualesSantaFe { get; set; }
        public virtual DbSet<LluviasDiariasBuenosAires> LluviasDiariasBuenosAires { get; set; }
        public virtual DbSet<LluviasDiariasSantaFe> LluviasDiariasSantaFe { get; set; }
    }
}
