//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promedio_diario_trigo
    {
        public Nullable<decimal> PromedioAnual { get; set; }
        public Nullable<decimal> PromedioMensual { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
